### ISSUE TITLE
Newer aiohttp does not accept loop arg in web.run_app

### ISSUE THREAD

**Issue by MarSoft** [nonamenix/aioviber#3]
When I try to use aioviber as per readme, I get the following error:
```
Traceback (most recent call last):
  File "app.py", line 43, in <module>
    bot.run()
  File "/tmp/env/lib/python3.7/site-packages/aioviber/bot.py", line 152, in run
    web.run_app(self.app, host=self.host, port=self.port, loop=self.loop)
TypeError: run_app() got an unexpected keyword argument 'loop'
/tmp/env/lib/python3.7/site-packages/aioviber/bot.py:157: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f69f68e4518>
```
Package versions:
```
python==3.7.3
aiohttp==3.5.4
aioviber==0.1.5
viberbot==1.0.11
```

**Comment by MarSoft** [comment]
Workaround: instead of `bot.run()`, use this:
```
import aiohttp.web
aiohttp.web.run_app(bot.app, host=bot.host, port=bot.port)
```
